// Packages préexistants scrapés depuis multiwex.be le 14/04/2026
// Sources : /fr/groupes/, /fr/anniversaires/, /fr/entreprises/

export const packages = [
  {
    id: 'anniv-mini',
    name: 'Anniversaire Mini',
    category: 'birthday',
    tagline: '8-16 ans · moins de 1m45',
    pricePerPerson: 26,
    minPlayers: 6,
    ageMin: 8,
    ageMax: 16,
    heightMax: 145,
    description: "Le package idéal pour les petits (moins de 1m45) qui veulent un anniversaire mémorable.",
    activities: [
      { activityId: 'eyestart', duration: 20, label: 'EyeStart VR' },
      { activityId: 'cube3', duration: 15, label: 'Cube3 Pixel Floor' },
      { activityId: 'buzzequiz', duration: 60, label: 'Buzz-e-Quiz', or: 'k7' },
    ],
    inclusions: ['1 soft drink par participant'],
    addons: [
      { id: 'starcadium', label: 'Carte Starcadium', price: 5 },
      { id: 'buffet-pizza', label: 'Buffet pizza + boissons', price: 10 },
      { id: 'buffet-sweet', label: 'Buffet sucré + boissons', price: 15 },
    ],
  },
  {
    id: 'anniv-maxi',
    name: 'Anniversaire Maxi',
    category: 'birthday',
    tagline: '8-16 ans · plus de 1m45',
    pricePerPerson: 38,
    minPlayers: 6,
    ageMin: 8,
    ageMax: 16,
    heightMin: 145,
    description: "Le package complet avec BattleKart pour les ados.",
    activities: [
      { activityId: 'battlekart', duration: 15, label: 'BattleKart', external: true },
      { activityId: 'eyestart', duration: 20, label: 'EyeStart VR' },
      { activityId: 'darkdrift', duration: 10, label: 'DarkDrift' },
      { activityId: 'cube3', duration: 15, label: 'Cube3' },
    ],
    inclusions: ['1 soft drink par participant'],
    addons: [
      { id: 'starcadium', label: 'Carte Starcadium', price: 5 },
      { id: 'buffet-pizza', label: 'Buffet pizza + boissons', price: 10 },
      { id: 'buffet-sweet', label: 'Buffet sucré + boissons', price: 15 },
    ],
    note: 'BattleKart est réservé via son système dédié — nous vous guidons après la confirmation.',
  },
  {
    id: 'evg',
    name: 'EVG',
    category: 'bachelor',
    tagline: 'Enterrement de vie de garçon',
    pricePerPerson: 49,
    minPlayers: 6,
    ageMin: 18,
    description: "La formule la plus testostéronée de Multiwex.",
    activities: [
      { activityId: 'battlekart', duration: 15, label: 'BattleKart', external: true },
      { activityId: 'slashhit', duration: 60, label: 'Slash and Hit', or: 'buzzequiz' },
      { activityId: 'eyestart', duration: 20, label: 'EyeStart VR' },
    ],
    inclusions: ['1 pils ou soft drink par participant'],
    note: 'BattleKart est réservé via son système dédié — nous vous guidons après la confirmation.',
  },
  {
    id: 'evjf',
    name: 'EVJF',
    category: 'bachelor',
    tagline: 'Enterrement de vie de jeune fille',
    pricePerPerson: 49,
    minPlayers: 6,
    ageMin: 18,
    description: "La formule parfaite pour une team au top.",
    activities: [
      { activityId: 'battlekart', duration: 15, label: 'BattleKart', external: true },
      { activityId: 'k7', duration: 60, label: 'K7 Karaoké', or: 'buzzequiz' },
      { activityId: 'eyestart', duration: 20, label: 'EyeStart VR' },
    ],
    inclusions: ['1 pils ou soft drink par participant'],
    note: 'BattleKart est réservé via son système dédié — nous vous guidons après la confirmation.',
  },
  {
    id: 'scolaires',
    name: 'Groupe scolaire',
    category: 'school',
    tagline: '-50% du lundi au vendredi',
    pricePerPerson: 10,
    minPlayers: 12,
    description: "Tarif spécial écoles (hors week-end). 1 accompagnant gratuit pour 11 élèves payants.",
    requiresQuote: true,
    contactUrl: 'https://www.multiwex.be/fr/entreprises/',
  },
  {
    id: 'jeunesse',
    name: 'Mouvements de jeunesse',
    category: 'youth',
    tagline: 'Spécial été · -50%',
    pricePerPerson: 10,
    minPlayers: 6,
    description: "Offre estivale pour les mouvements de jeunesse, sur réservation par email uniquement.",
    requiresQuote: true,
    contactUrl: 'https://www.multiwex.be/fr/entreprises/',
  },
  {
    id: 'b2b-battlekart',
    name: 'BattleKart Challenge',
    category: 'corporate',
    tagline: 'Team building ·BattleKart',
    pricePerPerson: 54,
    priceNote: 'HT / personne',
    minPlayers: 12,
    maxPlayers: 60,
    durationMin: 90,
    durationMax: 300,
    description: "3 courses BattleKart par personne, avec combinaison possible d'autres activités.",
    requiresQuote: true,
    contactUrl: 'https://www.multiwex.be/fr/entreprises/',
  },
  {
    id: 'b2b-multichallenge',
    name: 'MultiChallenge',
    category: 'corporate',
    tagline: 'Team building · équipes',
    pricePerPerson: 65,
    priceNote: 'HT / personne',
    minPlayers: 24,
    maxPlayers: 150,
    durationMin: 180,
    durationMax: 360,
    description: "Équipes de 6 qui s'affrontent sur plusieurs challenges. Fun, stratégie et esprit d'équipe.",
    requiresQuote: true,
    contactUrl: 'https://www.multiwex.be/fr/entreprises/',
  },
];

export function getPackage(id) {
  return packages.find((p) => p.id === id);
}

export function getPackagesByCategory(cat) {
  return packages.filter((p) => p.category === cat);
}
